version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'route-tracker-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: gunicorn route_tracker.wsgi:application --bind 0.0.0.0:5000 --workers 1
    volumes:
      - .:/app
    ports:
      - "5000:5000"